language: node_js
node_js:
  - "10.14.1"

# branches:
#   only:
#     - deploy

cache:
  directories:
    - node_modules

before_install:
  - npm install -g hexo-cli

install:
  - npm install

script:
  - "./bin/deploy"

after_script:
  - echo deployment completed!

notifications:
  email:
    recipients:
      - dcanetma@gmail.com
    on_success: always # default: never
    on_failure: always # default: always
